- frankfurt/bedrock-prod/deploy.yaml
- iowa-a/bedrock-prod/deploy.yaml
- iowa-a/bedrock-stage/deploy.yaml
Frankfurt stage failed, but this needs to go out. All [tests passed in oregon-b](https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/355/pipeline/).
> Force deployment of prod-55e91247

- frankfurt/bedrock-prod/deploy.yaml
- iowa-a/bedrock-prod/deploy.yaml
We shouldn't need to adjust the CSP header in prod as it already includes *.mozilla.org:
```
$ curl -Is www.mozilla.org | grep Content-Security
```
> Content-Security-Policy: script-src 'self' *.mozilla.net *.mozilla.org *.mozilla.com 'unsafe-inline' 'unsafe-eval' www.googletagmanager.com www.google-analytics.com tagmanager.google.com www.youtube.com s.ytimg.com; img-src 'self' *.mozilla.net *.mozilla.org *.mozilla.com data: mozilla.org www.googletagmanager.com www.google-analytics.com adservice.google.com adservice.google.de adservice.google.dk creativecommons.org ad.doubleclick.net; default-src 'self' *.mozilla.net *.mozilla.org *.mozilla.com; frame-src www.googletagmanager.com www.google-analytics.com www.youtube-nocookie.com trackertest.org www.surveygizmo.com accounts.firefox.com …
> Set STATIC_URL to https://www.mozilla.org/media/ in prod

- iowa-a/bedrock-dev/clock-deploy.yaml
The secrets were updated in https://github.com/mozmeao/infra-private/commit/dab25a01bb5372f40583b55044d7b60a00bfed29 and applied in iowa-a.
> Add Pocket API settings for mozmeao/infra#1003

- .gitlab-ci.yml
- bin/acceptance-tests.sh
- these were accidentally re-introduced during a rebase 
- fix #250 
- also add `only: $CI_PIPELINE_SOURCE == "push"` to dev, stage, and prod jobs
- workaround for https://gitlab.com/gitlab-org/gitlab-foss/issues/58961#note_204548994
- manually triggered https://gitlab.com/mozmeao/www-config/pipelines/100304421 with  BASE_URL=https://bedrock-prod.gcp.moz.works
> Remove case statements from bin/acceptance-test.sh

- frankfurt/bedrock-prod/deploy.yaml
- iowa-a/bedrock-prod/deploy.yaml
This should speed up prod deploys a bit. See also https://github.com/mozmeao/www-config/commit/e8737213864d785bf7370be40cd893ae7391732f where this was applied in dev & stage.
> Increase maxSurge to 5 in frankfurt & iowa-a prod

- .gitlab-ci.yml
- oregon-b/bedrock-test/configmap.yaml
- oregon-b/bedrock-test/deploy.yaml
- oregon-b/bedrock-test/ns.yaml
- oregon-b/bedrock-test/svc.yaml
This adds a dedicated deployment in oregon-b for integration test purposes. There will be a follow up PR to bedrock that updates this deployment and runs the integration tests on push to the `run-integration-tests` branch of bedrock. See also https://github.com/mozmeao/infra/issues/1185
> Add oregon-b/bedrock-test

- .gitlab-ci.yml
- https://docs.gitlab.com/ee/ci/yaml/#retry
- Add `retry: 2` to `.deploy` jobs
- Add `retry: 1` to `.test` jobs
This should reduce the need to retry deploy or test jobs manually, and we can tweak these values and/or override them on a per test basis as desired.
> Add retries to deploy & test jobs

- iowa-a/bedrock-prod/deploy.yaml
- iowa-a/bedrock-prod/hpa.yaml
It seems like the hpa doesn't typically scale up.
To save resources/money, let's scale down a bit and see if we get more usage per pod.
helps address mozmeao/infra#1292
> Reduce prod pod count

- .gitlab-ci.yml
- bin/acceptance-tests.sh
- bin/cleanup_after_functional_tests.sh
This adds jobs to run selenium tests in a local cluster running on the CI runner. It adds a global variable in the CI config called `SKIP_DRIVER`, which we'll set to `Remote` initially, which will cause it to not actually start the local selenium and run those tests. But it can be changed to `SauceLabs` to only run the non-sauce tests including the local selenium ones. This means we can merge this and use the switch whenever we need it. I'd love to hear your thoughts on the matter @alexgibson .
> Add local testing via selenium

- .gitlab-ci.yml
Following up on the work in https://github.com/mozilla/bedrock/pull/9210 this disables the download tests for dev deployments. The reasoning is that those run a lot and it is overkill to test all of these links (around 4700 at time of writing) for every merge to the main branch.
This leaves the download tests running for stage and prod deployments as well as the ones you can manually run and the run-integration-tests branch.
> Disable download tests for dev deployments

- .gitlab-ci.yml
Add mark expressions to some test runs to avoid even attempting tests that aren't applicable to the current browser.
> Add more mark expressions to efficiently skip tests

- .gitlab-ci.yml
- bin/acceptance-tests.sh
- bin/cleanup_after_functional_tests.sh
- docker-compose.yml
Second commit will be removed before merging, only there for testing
Test run https://gitlab.com/mozmeao/www-config/-/pipelines/204608823
- Firefox, Chrome runs on runners
- Replaced xdist with parallel. See https://github.com/mozilla/bedrock/pull/9565
- Failed tests upload Screenshots and logs on Gitab, accessible via the IU
- Tests take about ~16-20 minutes to complete (on a `c5a` runner, see https://github.com/mozmeao/infra/issues/1359)
This is still in progress but I'd like your feedback @alexgibson @pmac. It's missing re-running failed tests on Saucelabs to get videos.
> Local Selenium Grid

- .gitlab-ci.yml
- bin/cleanup_after_functional_tests.sh
So we can still run manual saucelabs jobs after a few days.
> Expire dotenv artifacts in a week.

- iowa-a/bedrock-dev/deploy.yaml
- iowa-a/bedrock-prod/deploy.yaml
- iowa-a/bedrock-stage/deploy.yaml
- iowa-a/bedrock-test/deploy.yaml
Startup seems to require more resources, so the pods are failing to come to ready.  This should solve that for now.
> Bumping size up

- iowa-a/bedrock-test/deploy.yaml
Giving more resources to the test deployment, because we're observing more some sysexits
> Increasing bedrock test resources increase

- iowa-a/bedrock-dev/deploy.yaml
- iowa-a/bedrock-stage/deploy.yaml
- iowa-a/bedrock-test/deploy.yaml
this worker type was an experiement that we ended up moving to a canary deploy
and then the canary deploy told us we shouldn't promote
but it seems we didn't flow that back to the canary deploy
> Removing gevent from non prod environments

- iowa-a/bedrock-dev/vpa.yaml
- iowa-a/bedrock-prod/vpa.yaml
- iowa-a/bedrock-stage/vpa.yaml
- mozmeao-fr/bedrock-prod/vpa.yaml
VPAs seems to be thrashing the pods in the cluster, reverting these back to info only.
> turning off vpa autoupdating

- mozmeao-fr/bedrock-prod/ingress-controller.sh
Bedrock is currently on kubeVersion v1.17.17-eks-087e67, but the ingress-nginx module [v1.0.0 includes a breaking change](https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.0.1/Changelog.md#100) that requires kube 1.19.0-0. So this pins our module to v0.*, so that we can keep up on v0 updates (if any) while avoiding the v1+ until our kube catches up.
> bedrock: Pin ingress-nginx to v0.* to defer Kubernetes upgrade

- mozmeao-fr/bedrock-prod/ingress-controller.sh
In #393, I pinned the appVersion rather than [the helm chart version](https://github.com/kubernetes/ingress-nginx/commit/f3c50698d98299b1a61f83cb6c4bb7de0b71fb4b#diff-e72ddd685185c5bc7e7b0a56fc62629956c75d5d3d4a15f2c92c5cd0ba3b0d4eR5). This corrects that.
> bedrock-fr: Pin ingress-nginx *chart* to 3.36.0 to defer Kubernetes upgrade

- iowa-a/bedrock-prod/canary-deploy.yaml
- iowa-a/bedrock-prod/clock-deploy.yaml
- iowa-a/bedrock-prod/daemonset.yaml
- iowa-a/bedrock-prod/deploy.yaml
- mozmeao-fr/bedrock-prod/canary-deploy.yaml
- mozmeao-fr/bedrock-prod/daemonset.yaml
- mozmeao-fr/bedrock-prod/deploy.yaml
This changeset complements work done in https://github.com/mozilla/bedrock/pull/10727
We're making a frontend-specific Sentry DSN available only in production. 
If it's not available, bedrock site will fall back to the current behaviour of using the same DSN for FE and BE error-logging
Part of work towards [#10593](https://github.com/mozilla/bedrock/issues/10593)
> Add a separate frontend-specific Sentry DSN for production ONLY

- iowa-a/bedrock-dev/clock-deploy.yaml
- iowa-a/bedrock-prod/clock-deploy.yaml
- iowa-a/bedrock-stage/clock-deploy.yaml
As part of https://github.com/mozilla/bedrock/issues/10814 we're adding one new type of snitch, which is called after Bedrock's DB updater script has been run. 
The new snitch URLs for dev, stage and prod have already been set up (in pause mode) and have been added to the secrets store, so this changeset references them to be pulled in as env vars.
> Add env vars for new DMS to ping after run-db-update.sh

- iowa-a/bedrock-test/pocket-deploy.yaml
Noticed that `test.tekcopteg.com` was not rendering correctly because of CSP to the gcp domain. Updated to point at the test.tekcopteg.com domain.
> chore(pocket-test): Point at test domain

- mozmeao-fr/bedrock-prod/ingress.yml
Upgrading some deprecated APIs in anticipation of an upgrade to 1.22
> chore(k8s): Update deprecated APIs

- iowa-a/bedrock-dev/pocket-deploy.yaml
- iowa-a/bedrock-prod/pocket-deploy.yaml
- iowa-a/bedrock-stage/pocket-deploy.yaml
- iowa-a/bedrock-test/pocket-deploy.yaml
- requirements.txt
* Upgrades mkdocs, following security ping by Github. Downside is we have to downpin Jinja2 to ensure docs still build
* Remove redundant GTM ID for Pocket Mode
* Add Google Analytics ID for Pocket Mode (not secret, because it's a GA ID that'll be in the HTML template)
> Updates for GA in Pocket Mode + sec bump

- iowa-a/bedrock-stage/clock-deploy.yaml
Note that, unlike dev, stage does not preview live content, so only the clock pod has Contentful config
> Make Stage use pre-production as its Contentful environment

- .gitlab-ci.yml
Retain new-infra tests, of course
This should reduce load on the Gitlab CI runners, which are doing double duty running tests against old and new infra at the same time, resulting in (I suspect...) a bit of a traffic jam that can get out of hand and swamp the runners. 
Will revert if this does not improve runner happiness levels
> Disable running Dev and Staging tests against the older GCP infra

- iowa-a/bedrock-dev/pocket-deploy.yaml
- iowa-a/bedrock-prod/pocket-deploy.yaml
- iowa-a/bedrock-stage/pocket-deploy.yaml
- iowa-a/bedrock-test/pocket-deploy.yaml
Related to [this](https://github.com/mozilla/bedrock/pull/12433) PR on bedrock. This adds the GTM_CONTAINER_ID for the pocket deploys
> Add GTM_CONTAINER_ID for pocket deploy

- .gitlab-ci.yml
- bin/acceptance-tests.sh
Add `BOUNCER_URL` for Dev only, so our tests are expecting the same domain for downloads as www-dev is now serving.
www-dev is on new infra, so uses the new config repo, while the tests are using the older conifg (this repo) which had no knowledge of www-dev now using a different,non-default `BOUNCER_URL`
> Update bouncer config to fix Gitlab CI tests that are hitting the new infra 

- iowa-a/bedrock-dev/pocket-deploy.yaml
- iowa-a/bedrock-stage/pocket-deploy.yaml
- iowa-a/bedrock-test/pocket-deploy.yaml
~We should not be running GA4 GTM scripts from any environment other than prod because we do not have views or hostname filter options on the resulting data (as in Universal Analytics).~
We have solved the GA4 filter issue with a [GTM config change](https://github.com/mozilla/bedrock/issues/12630). This PR will update GTM IDs on all environments and does not need to delete any.
related to https://github.com/mozilla/bedrock/pull/12638
> Update Pocket GTM Container settings

- iowa-a/bedrock-prod/pocket-deploy.yaml
Follow up from https://github.com/mozmeao/www-config/pull/503
Tested from stage and ready to deploy new GTM Container ID in prod
Once in prod, the GTM container should connect to prod GA4 id (starts with `G-RBR`)
> Update pocket prod GTM container ID
