mozmeao/www-config

Jenkinsfile, bin/publish-docs.sh, docs/index.md
=> Rename mozmar github org to mozmeao

bedrock-prod/deploy.yaml, bedrock-stage/deploy.yaml
See https://github.com/mozilla/bedrock/pull/5758 and specifically https://github.com/mozilla/bedrock/pull/5758/files#diff-7194d3de4cc9718f18e49e996f1e50b0
Also see https://github.com/mozmeao/www-config/pull/112
=> [bug 1463821] Add SMS countries for Fx61 whatsnew page

configs/tokyo.env, docs/index.md, jenkins/branches/bedrock-dev.yml, jenkins/branches/bedrock-stage.yml, jenkins/regions.yml
https://github.com/mozmeao/infra/issues/924
https://github.com/mozilla/bedrock/pull/6165
we'll need to coordinate this with a route53 change to take Tokyo out of the traffic policy.
cc @jgmize @pmac @jpetto
=> remove tokyo!

frankfurt/bedrock-stage/deploy.yaml, iowa-a/bedrock-stage/deploy.yaml
Shouldn't merge until mozilla/bedrock#6488 lands.
=> Enable FxA OAuth relier on stage.

frankfurt/bedrock-prod/deploy.yaml, iowa-a/bedrock-prod/deploy.yaml, iowa-a/bedrock-stage/deploy.yaml
Continuation of failed Jenkins job:
https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/prod/352/pipeline/
=> Deploy 00644b52163 to the remainder of the clusters

iowa-a/bedrock-stage/deploy.yaml
For mozmeao/infra#1009
Eliminate redundant values from CSP_DEFAULT_SRC
=> Add CONTENT_CARDS_BRANCH to stage deployment in iowa-a

frankfurt/bedrock-prod/deploy.yaml, iowa-a/bedrock-prod/deploy.yaml
=> Add CONTENT_CARDS_BRANCH to prod deployments in iowa-a and frankfurt

iowa-a/bedrock-prod/clock-deploy.yaml
- `deis ps:scale clock=0 -a bedrock-prod`
=> Add clock deployment to iowa-a for mozmeao/infra#1003

iowa-a/bedrock-prod/clock-deploy.yaml
=> Add DEAD_MANS_SNITCH_URL to prod clock deployment in iowa-a

iowa-a/bedrock-dev/clock-deploy.yaml, iowa-a/bedrock-stage/clock-deploy.yaml
Re https://github.com/mozmeao/infra/issues/1010
=> Update dev and stage clock pod images

iowa-a/bedrock-stage/clock-deploy.yaml, iowa-a/bedrock-stage/deploy.yaml
Re https://github.com/mozmeao/www-admin/pull/18
=> Update content cards git branch for bedrock stage

.gitlab-ci.yml, bin/acceptance-tests.sh, bin/rollout-status.sh, iowa-a/bedrock-dev/clock-deploy.yaml, iowa-a/bedrock-dev/configmap.yaml, iowa-a/bedrock-dev/deploy.yaml, iowa-a/bedrock-dev/hpa.yaml, iowa-a/bedrock-dev/svc.yaml
Extracted and refactored dev-only version of #237 
- new dependency of https://github.com/mozilla/bedrock/pull/7926
- stage and prod will be in turn extracted into separate PRs with corresponding bedrock PRs after this is merged
=> Gitlab CI/CD dev-only

.gitlab-ci.yml, iowa-a/bedrock-stage/clock-deploy.yaml, iowa-a/bedrock-stage/configmap.yaml, iowa-a/bedrock-stage/deploy.yaml, iowa-a/bedrock-stage/hpa.yaml, iowa-a/bedrock-stage/svc.yaml
copy configs from git-sync-operator branch commit 28ef287
=> Add stage deploy and test jobs and configs

.gitlab-ci.yml, frankfurt/bedrock-prod/configmap.yaml, frankfurt/bedrock-prod/deploy.yaml, frankfurt/bedrock-prod/hpa.yaml, frankfurt/bedrock-prod/svc.yaml, iowa-a/bedrock-prod/clock-deploy.yaml, iowa-a/bedrock-prod/configmap.yaml, iowa-a/bedrock-prod/deploy.yaml, iowa-a/bedrock-prod/hpa.yaml, iowa-a/bedrock-prod/svc.yaml
- based on https://github.com/mozmeao/www-config/pull/246 
- to be merged after successful stage pipeline resulting from merging ^ to master
=> Gitlab CI prod

.gitlab-ci.yml, bin/acceptance-tests.sh
Running this against with a BASE_URL of https://bedrock-prod.gcp.moz.works at https://gitlab.com/mozmeao/www-config/pipelines/100420665
=> Add PYTEST_PROCESSES to bin/acceptance-tests.sh and default to 4

iowa-a/bedrock-prod/deploy.yaml
update in bigger batches
allow more time for changes to occur
change maxunavailable to a percentage
=> Make the iowa-a deployment more reliable

.editorconfig, iowa-a/bedrock-dev/daemonset.yaml
I have a bedrock PR that will move the database and the l10n files into this `data` directory:
https://github.com/mozilla/bedrock/pull/8900
=> Add a DaemonSet for bedrock-dev data update

frankfurt/bedrock-prod/deploy.yaml, iowa-a/bedrock-dev/clock-deploy.yaml, iowa-a/bedrock-dev/daemonset.yaml, iowa-a/bedrock-dev/deploy.yaml, iowa-a/bedrock-prod/clock-deploy.yaml, iowa-a/bedrock-prod/deploy.yaml, iowa-a/bedrock-stage/clock-deploy.yaml, iowa-a/bedrock-stage/deploy.yaml, oregon-b/bedrock-test/deploy.yaml
Support for https://github.com/mozilla/bedrock/pull/9180 and https://github.com/mozilla/bedrock/pull/9183
=> Update Sentry DSN to new non-secret form

.gitlab-ci.yml
Resource group per unique job to limit to one running job.
=> Limit number of tests that can run at one time

iowa-a/bedrock-prod/clock-deploy.yaml, iowa-a/bedrock-test/deploy.yaml
=> Add docker secret to the rest of the deployments

iowa-a/bedrock-dev/deploy.yaml
The gevent threads were failing to come to ready
=> Allowing the pods to have more resources

iowa-a/bedrock-prod/canary-deploy.yaml, iowa-a/bedrock-stage/canary-deploy.yaml, mozmeao-fr/bedrock-prod/canary-deploy.yaml
deploying the debug images as canary deploys
=> Adding some canary deploys to make debug images

docker-compose.yml, iowa-a/bedrock-dev/hpa.yaml
trying to pin to a slightly older version of the chrome container
=> Getting failures in the pipeline, bind failing

iowa-a/bedrock-stage/clock-deploy.yaml
=> Add SQS/Contentful env vars for Stage, pulling from secrets

iowa-a/bedrock-prod/clock-deploy.yaml
Stage-only changes from #420 - **do not merge** until #421 is merged _and_ tested on stage
Resolves #10773
=> Add SQS/Contentful env vars for Prod, pulling from secrets

mozmeao-fr/bedrock-prod/ingress.yml
Seems to break deployment, so reverting the change
=> Reverting change

.gitlab-ci.yml, .gitlab/environment_tests.yml
No cdn for test, so skipping running these tests
Adding a resource lock to try and debug failures
=> A few small cdn test fixes

iowa-a/bedrock-dev/clock-deploy.yaml, iowa-a/bedrock-dev/daemonset.yaml, iowa-a/bedrock-dev/deploy.yaml, iowa-a/bedrock-stage/clock-deploy.yaml, iowa-a/bedrock-stage/daemonset.yaml, iowa-a/bedrock-stage/deploy.yaml, iowa-a/bedrock-test/deploy.yaml
Updates dev, stage and test. Prod will come later
=> Update Bedrock Sentry DSNs to use new Sentry service

.gitlab-ci.yml, .gitlab/deployment_tests.yml, docs/index.md
See https://github.com/mozilla/bedrock/issues/9894
=> Update references to default branch to "main"

bin/acceptance-tests.sh, iowa-a/bedrock-dev/edit-me-to-trigger-the-main-pipeline.txt
+ bump a new build of main/dev
=> Fixup bouncer url env var fallback
